[tool.poetry]
name = "wealth-management"
version = "0.1.0"
description = ""
authors = ["MarcHansen95 <marchansen95@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
